# Introduction: We now need to provide information regarding the docker image we plan to use.

# Instruction: Add a property containers under spec section. Do not add anything under it yet.
#
# ------------------------------
#           BEFORE
# ------------------------------
#apiVersion: v1
#kind: Pod
#metadata:
#  name: myapp-pod
#  labels:
#    app: myapp
#spec:

# ------------------------------
#           AFTER
# ------------------------------

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers: