# Introduction: The template section expects a Pod definition. Luckily, we have the one we created in the previous set of exercises. Next to the deployment-definition.yml you will now find the same pod-definition.yml file that you created before.
# Instruction: Let us now copy the contents of the pod-definition.yml file, except for the apiVersion and kind and place it under the template section.
# Take extra care on moving the contents to the right so it falls under template.
# ------------------------------
#           BEFORE
# ------------------------------
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: frontend
#  labels:
#    app: mywebsite
#    tier: frontend
#spec:
#  replicas: 4
#  template:
#  selector:

# ------------------------------
#           AFTER
# ------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: mywebsite
    tier: frontend
spec:
  replicas: 4
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  selector: