# Instruction: Let us update the number of replicas to 4.
# ------------------------------
#           BEFORE
# ------------------------------
#apiVersion: apps/v1
#kind: ReplicaSet
#metadata:
#  name: frontend
#  labels:
#    app: mywebsite
#    tier: frontend
#spec:
#  replicas: 4
#  template:
#  selector:

# ------------------------------
#           AFTER
# ------------------------------

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: mywebsite
    tier: frontend
spec:
  replicas: 4
  template:
  selector: